web:
  build: .
  ports:
    - '4000:4000'
  links:
    - db
  volumes:
    - '.:/u/app'
  command: mix phoenix.server
  environment:
    - DATABASE_URL="jdbc://brdcaster:raposa@192.168.99.100/brdcaster"

db:
  image: postgres:9.6
  ports:
  - "5432:5432"
  volumes:
    - data:/var/lib/postgresql/data
  environment:
    - POSTGRES_PASSWORD=raposa
    - POSTGRES_USER=brdcaster

redis:
  image: redis:3.0.7
  ports:
  - "6379:6379"
  volumes:
    - data:/var/lib/redis/data

